// data.js - 截至 2026年6月底 的模拟聚合数据（仅供演示参考）
const aiData = [
  {
    id: "claude-fable-5",
    vendor: "Anthropic",
    model: "Claude Fable 5",
    updateDate: "2026-06-09",
    inputPrice: 10.0,
    outputPrice: 50.0,
    contextWindow: 1000000,
    intelligence: 60,
    speed: 59,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "computer", "code"],
    openWeights: false,
    notes: "Mythos 级别前沿模型，长时程 agent 能力极强",
    officialUrl: "https://www.anthropic.com/claude/fable"
  },
  {
    id: "claude-opus-4-8",
    vendor: "Anthropic",
    model: "Claude Opus 4.8",
    updateDate: "2026-05-28",
    inputPrice: 5.0,
    outputPrice: 25.0,
    contextWindow: 1000000,
    intelligence: 56,
    speed: 59,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "computer", "code"],
    openWeights: false,
    notes: "复杂 agentic 任务与企业工作首选",
    officialUrl: "https://www.anthropic.com/claude/opus"
  },
  {
    id: "claude-sonnet-4-6",
    vendor: "Anthropic",
    model: "Claude Sonnet 4.6",
    updateDate: "2026-06-23",
    inputPrice: 3.0,
    outputPrice: 15.0,
    contextWindow: 1000000,
    intelligence: 47,
    speed: 50,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "code"],
    openWeights: false,
    notes: "智能、速度、成本最佳平衡",
    officialUrl: "https://www.anthropic.com/claude/sonnet"
  },
  {
    id: "claude-haiku-4-5",
    vendor: "Anthropic",
    model: "Claude Haiku 4.5",
    updateDate: "2026-04-10",
    inputPrice: 1.0,
    outputPrice: 5.0,
    contextWindow: 200000,
    intelligence: 30,
    speed: 98,
    multimodal: true,
    reasoning: false,
    tools: ["function", "code"],
    openWeights: false,
    notes: "最快最便宜的 Claude 系列",
    officialUrl: "https://www.anthropic.com/claude/haiku"
  },
  {
    id: "gpt-5-5-xhigh",
    vendor: "OpenAI",
    model: "GPT-5.5 (xhigh)",
    updateDate: "2026-06-01",
    inputPrice: 5.0,
    outputPrice: 30.0,
    contextWindow: 1000000,
    intelligence: 55,
    speed: 80,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "computer", "code"],
    openWeights: false,
    notes: "编码与专业工作顶级智能",
    officialUrl: "https://platform.openai.com/docs/models/gpt-5-5"
  },
  {
    id: "gpt-5-4-mini",
    vendor: "OpenAI",
    model: "GPT-5.4 mini",
    updateDate: "2026-05-20",
    inputPrice: 0.75,
    outputPrice: 4.5,
    contextWindow: 400000,
    intelligence: 40,
    speed: 183,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "code"],
    openWeights: false,
    notes: "性价比极高的迷你模型",
    officialUrl: "https://platform.openai.com/docs/models/gpt-5-4-mini"
  },
  {
    id: "gpt-5-4-nano",
    vendor: "OpenAI",
    model: "GPT-5.4 nano",
    updateDate: "2026-05-15",
    inputPrice: 0.18,
    outputPrice: 1.1,
    contextWindow: 400000,
    intelligence: 38,
    speed: 166,
    multimodal: true,
    reasoning: false,
    tools: ["function", "code"],
    openWeights: false,
    notes: "极致低成本高吞吐",
    officialUrl: "https://platform.openai.com/docs/models/gpt-5-4-nano"
  },
  {
    id: "gemini-3-5-flash",
    vendor: "Google",
    model: "Gemini 3.5 Flash",
    updateDate: "2026-06-15",
    inputPrice: 1.31,
    outputPrice: 5.24,
    contextWindow: 1000000,
    intelligence: 50,
    speed: 170,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "code"],
    openWeights: false,
    notes: "Agent 与编码前沿性能，性价比突出",
    officialUrl: "https://deepmind.google/models/gemini/"
  },
  {
    id: "gemini-3-1-pro",
    vendor: "Google",
    model: "Gemini 3.1 Pro",
    updateDate: "2026-05-10",
    inputPrice: 1.74,
    outputPrice: 10.5,
    contextWindow: 1000000,
    intelligence: 46,
    speed: 137,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "code"],
    openWeights: false,
    notes: "复杂任务与创意生成强项",
    officialUrl: "https://deepmind.google/models/gemini/"
  },
  {
    id: "grok-build-0-1",
    vendor: "xAI",
    model: "Grok Build 0.1 0616",
    updateDate: "2026-06-16",
    inputPrice: 0.54,
    outputPrice: 2.7,
    contextWindow: 256000,
    intelligence: 40,
    speed: 102,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web"],
    openWeights: false,
    notes: "实时知识与工具调用表现优秀",
    officialUrl: "https://x.ai"
  },
  {
    id: "deepseek-v4-pro",
    vendor: "DeepSeek",
    model: "DeepSeek V4 Pro",
    updateDate: "2026-06-20",
    inputPrice: 0.18,
    outputPrice: 0.54,
    contextWindow: 1000000,
    intelligence: 44,
    speed: 88,
    multimodal: true,
    reasoning: true,
    tools: ["function", "code"],
    openWeights: false,
    notes: "极致低价的高性能推理模型",
    officialUrl: "https://platform.deepseek.com"
  },
  {
    id: "deepseek-v4-flash",
    vendor: "DeepSeek",
    model: "DeepSeek V4 Flash",
    updateDate: "2026-06-18",
    inputPrice: 0.06,
    outputPrice: 0.18,
    contextWindow: 1000000,
    intelligence: 37,
    speed: 110,
    multimodal: false,
    reasoning: false,
    tools: ["function"],
    openWeights: false,
    notes: "最便宜的超长上下文选项",
    officialUrl: "https://platform.deepseek.com"
  },
  {
    id: "qwen3-7-max",
    vendor: "Alibaba",
    model: "Qwen3.7 Max",
    updateDate: "2026-06-12",
    inputPrice: 1.43,
    outputPrice: 4.3,
    contextWindow: 1000000,
    intelligence: 46,
    speed: 200,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web", "code"],
    openWeights: false,
    notes: "中文与多语言能力极强",
    officialUrl: "https://www.aliyun.com/product/dashscope"
  },
  {
    id: "glm-5-2",
    vendor: "Zhipu AI",
    model: "GLM-5.2 (max)",
    updateDate: "2026-06-16",
    inputPrice: 0.90,
    outputPrice: 2.7,
    contextWindow: 1000000,
    intelligence: 51,
    speed: 129,
    multimodal: true,
    reasoning: true,
    tools: ["function", "web"],
    openWeights: true,
    notes: "开源权重领先模型之一",
    officialUrl: "https://open.bigmodel.cn"
  },
  {
    id: "kimi-k2-7-code",
    vendor: "Kimi",
    model: "Kimi K2.7 Code",
    updateDate: "2026-06-08",
    inputPrice: 0.70,
    outputPrice: 2.1,
    contextWindow: 256000,
    intelligence: 42,
    speed: 63,
    multimodal: false,
    reasoning: true,
    tools: ["function", "code"],
    openWeights: false,
    notes: "代码与长文档理解专长",
    officialUrl: "https://kimi.moonshot.cn"
  },
  {
    id: "minimax-m3",
    vendor: "MiniMax",
    model: "MiniMax-M3",
    updateDate: "2026-06-08",
    inputPrice: 0.22,
    outputPrice: 0.66,
    contextWindow: 1000000,
    intelligence: 44,
    speed: 86,
    multimodal: true,
    reasoning: true,
    tools: ["function"],
    openWeights: true,
    notes: "长上下文开放权重模型代表",
    officialUrl: "https://www.minimax.io"
  },
  {
    id: "mistral-medium-3-5",
    vendor: "Mistral",
    model: "Mistral Medium 3.5",
    updateDate: "2026-05-25",
    inputPrice: 1.16,
    outputPrice: 3.5,
    contextWindow: 256000,
    intelligence: 30,
    speed: 121,
    multimodal: true,
    reasoning: false,
    tools: ["function", "code"],
    openWeights: false,
    notes: "欧洲厂商高效多模态模型",
    officialUrl: "https://mistral.ai"
  }
];

// 暴露到全局
window.aiData = aiData;
